import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const summaryPath = path.join(rootDir, "tools", "hero_implementation_inputs.summary.json");
const outputPath = path.join(rootDir, "src", "wujiang", "heroes", "excel_roster_data.py");

function pyString(value) {
  return JSON.stringify(value ?? "");
}

function pyValue(value) {
  if (typeof value === "number") return Number.isInteger(value) ? String(value) : String(value);
  return pyString(value);
}

function specToPython(hero) {
  const skillFragments = hero.skillFragments.map((fragment) => (
    `            {"name": ${pyString(fragment.name)}, "fragment": ${pyString(fragment.fragment)}, "common": ${fragment.common ? "True" : "False"}},`
  )).join("\n");
  const traitFragments = hero.traitFragments.map((fragment) => (
    `            {"fragment": ${pyString(fragment.fragment)}, "common": ${fragment.common ? "True" : "False"}},`
  )).join("\n");
  return `    {
        "code": "excel_r${String(hero.sourceRow).padStart(3, "0")}",
        "source_row": ${hero.sourceRow},
        "name": ${pyString(hero.name)},
        "level": ${pyValue(hero.stats.level)},
        "role": ${pyString(hero.stats.role)},
        "attribute": ${pyString(hero.stats.attribute)},
        "race": ${pyString(hero.stats.race)},
        "attack": ${pyValue(hero.stats.attack)},
        "defense": ${pyValue(hero.stats.defense)},
        "speed": ${pyValue(hero.stats.speed)},
        "range": ${pyValue(hero.stats.range)},
        "mana": ${pyValue(hero.stats.mana)},
        "raw_skill_text": ${pyString(hero.rawSkillText)},
        "raw_trait_text": ${pyString(hero.rawTraitText)},
        "skill_fragments": [
${skillFragments}
        ],
        "trait_fragments": [
${traitFragments}
        ],
    },`;
}

async function readSummary() {
  try {
    return JSON.parse(await fs.readFile(summaryPath, "utf8"));
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
    await import("./summarize_hero_implementation_inputs.mjs");
    return JSON.parse(await fs.readFile(summaryPath, "utf8"));
  }
}

const summary = await readSummary();
const body = `# Generated by tools/build_excel_roster_data.mjs from data/武将yoo.xlsx and docs/武将实现问题清单.xlsx.
# Do not edit this file by hand; update the source workbook/questionnaire and regenerate.

EXCEL_HERO_SPECS = [
${summary.heroes.map(specToPython).join("\n")}
]
`;

await fs.writeFile(outputPath, body, "utf8");
console.log(JSON.stringify({ outputPath, heroCount: summary.heroes.length }, null, 2));
